import type { Concern, Product, ProductCategory, SkinType, BudgetRange, AcneType } from "./types";

export type CatalogProduct = {
  name: string;
  category: ProductCategory;
  brand: string;
  clean?: boolean;
  price?: number;
  affiliateUrl?: string;
  tags: {
    concerns: Concern[];
    skinTypes: SkinType[];
    budgets: BudgetRange[];
    acneTypes?: AcneType[];
  };
  notes: string;
};

// Comprehensive clean beauty product database (200+ products)
export const CATALOG: CatalogProduct[] = [
  // ===== CLEANSERS =====
  { name: "Youth To The People Superfood Cleanser", category: "Cleanser", brand: "Youth To The People", clean: true, price: 36, affiliateUrl: "https://www.sephora.com/product/superfood-antioxidant-cleanser-P416155", tags: { concerns: ["Dullness"], skinTypes: ["Normal", "Combination", "Oily"], budgets: ["mid"] }, notes: "Antioxidant-rich for all skin" },
  { name: "La Roche-Posay Toleriane Hydrating Cleanser", category: "Cleanser", brand: "La Roche-Posay", clean: true, price: 15, affiliateUrl: "https://www.amazon.com/dp/B01N7T7JKJ", tags: { concerns: ["Sensitivity", "Redness", "Dehydration"], skinTypes: ["Dry", "Sensitive", "Normal"], budgets: ["budget"] }, notes: "Gentle, non-stripping, fragrance-free" },
  { name: "CeraVe Hydrating Facial Cleanser", category: "Cleanser", brand: "CeraVe", clean: true, price: 10, affiliateUrl: "https://www.amazon.com/dp/B01MSSDEPK", tags: { concerns: ["Dehydration", "Sensitivity"], skinTypes: ["Dry", "Normal", "Sensitive"], budgets: ["budget"] }, notes: "Barrier-friendly with ceramides" },
  { name: "CeraVe Foaming Facial Cleanser", category: "Cleanser", brand: "CeraVe", clean: true, price: 10, affiliateUrl: "https://www.amazon.com/dp/B003YMJJSK", tags: { concerns: ["Acne", "Large Pores"], skinTypes: ["Oily", "Combination", "Normal"], budgets: ["budget"], acneTypes: ["comedonal"] }, notes: "Oil control without over-drying" },
  { name: "Vanicream Gentle Facial Cleanser", category: "Cleanser", brand: "Vanicream", clean: true, price: 9, affiliateUrl: "https://www.amazon.com/dp/B00QY1XZ4W", tags: { concerns: ["Sensitivity", "Redness"], skinTypes: ["Sensitive", "Dry", "Normal"], budgets: ["budget"] }, notes: "Ultra-gentle, dermatologist recommended" },
  { name: "COSRX Low pH Good Morning Gel Cleanser", category: "Cleanser", brand: "COSRX", clean: true, price: 12, affiliateUrl: "https://www.amazon.com/dp/B016NRVIS0", tags: { concerns: ["Acne", "Large Pores"], skinTypes: ["Oily", "Combination"], budgets: ["budget"], acneTypes: ["comedonal", "inflammatory"] }, notes: "pH-balanced for healthy barrier" },
  { name: "Krave Beauty Matcha Hemp Hydrating Cleanser", category: "Cleanser", brand: "Krave Beauty", clean: true, price: 16, affiliateUrl: "https://kravebeauty.com/products/matcha-hemp-hydrating-cleanser", tags: { concerns: ["Dehydration", "Sensitivity"], skinTypes: ["Dry", "Normal", "Sensitive"], budgets: ["budget", "mid"] }, notes: "Non-stripping, great for all skin" },
  { name: "Glossier Milky Jelly Cleanser", category: "Cleanser", brand: "Glossier", clean: true, price: 18, affiliateUrl: "https://www.glossier.com/products/milky-jelly-cleanser", tags: { concerns: ["Sensitivity"], skinTypes: ["Normal", "Combination", "Dry"], budgets: ["mid"] }, notes: "Gentle daily cleanser" },
  { name: "La Roche-Posay Effaclar Cleanser", category: "Cleanser", brand: "La Roche-Posay", clean: true, price: 15, affiliateUrl: "https://www.amazon.com/dp/B00IW99WY8", tags: { concerns: ["Acne", "Large Pores"], skinTypes: ["Oily", "Combination"], budgets: ["budget"], acneTypes: ["comedonal", "inflammatory"] }, notes: "Targets excess oil and breakouts" },
  { name: "Fresh Soy Face Cleanser", category: "Cleanser", brand: "Fresh", clean: true, price: 38, affiliateUrl: "https://www.sephora.com/product/soy-face-cleanser", tags: { concerns: ["Dullness", "Dehydration"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["mid", "luxury"] }, notes: "Gentle, removes makeup" },
  
  // ===== DOUBLE CLEANSERS =====
  { name: "The INKEY List Oat Cleansing Balm", category: "Double Cleanser", brand: "The INKEY List", clean: true, price: 10, affiliateUrl: "https://www.sephora.com/product/oat-cleansing-balm", tags: { concerns: ["Sensitivity", "Dehydration"], skinTypes: ["Dry", "Normal", "Sensitive"], budgets: ["budget"] }, notes: "Soothing first cleanse" },
  { name: "Banila Co Clean It Zero Cleansing Balm", category: "Double Cleanser", brand: "Banila Co", clean: true, price: 19, affiliateUrl: "https://www.amazon.com/dp/B0719SBN6B", tags: { concerns: ["Large Pores"], skinTypes: ["Oily", "Combination", "Normal"], budgets: ["budget", "mid"] }, notes: "Melts makeup and sunscreen" },
  { name: "Then I Met You Living Cleansing Balm", category: "Double Cleanser", brand: "Then I Met You", clean: true, price: 38, affiliateUrl: "https://www.sephora.com/product/living-cleansing-balm", tags: { concerns: ["Dullness", "Dehydration"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["mid", "luxury"] }, notes: "Luxurious texture, thorough cleanse" },
  { name: "Heimish All Clean Balm", category: "Double Cleanser", brand: "Heimish", clean: true, price: 16, affiliateUrl: "https://www.amazon.com/dp/B01KXK152E", tags: { concerns: ["Sensitivity"], skinTypes: ["Normal", "Dry", "Sensitive"], budgets: ["budget", "mid"] }, notes: "Great for sensitive skin" },
  
  // ===== TONERS =====
  { name: "Paula's Choice Pore-Reducing Toner", category: "Toner", brand: "Paula's Choice", clean: true, price: 24, affiliateUrl: "https://www.paulaschoice.com/", tags: { concerns: ["Large Pores", "Acne"], skinTypes: ["Oily", "Combination"], budgets: ["mid"] }, notes: "Minimizes pores" },
  { name: "Thayers Witch Hazel Toner", category: "Toner", brand: "Thayers", clean: true, price: 12, affiliateUrl: "https://www.amazon.com/dp/B00016XJ4M", tags: { concerns: ["Large Pores", "Redness"], skinTypes: ["Normal", "Combination", "Oily"], budgets: ["budget"] }, notes: "Alcohol-free, gentle" },
  { name: "IUNIK Centella Calming Toner", category: "Toner", brand: "IUNIK", clean: true, price: 16, affiliateUrl: "https://www.amazon.com/dp/B07KXLD4XQ", tags: { concerns: ["Redness", "Sensitivity", "Acne"], skinTypes: ["Sensitive", "Combination", "Normal"], budgets: ["budget", "mid"], acneTypes: ["inflammatory"] }, notes: "Calms irritation and redness" },
  { name: "I'm From Rice Toner", category: "Toner", brand: "I'm From", clean: true, price: 25, affiliateUrl: "https://www.amazon.com/dp/B07YCMWL8X", tags: { concerns: ["Dullness", "Dehydration"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["mid"] }, notes: "Brightening and hydrating" },
  { name: "Klairs Supple Preparation Unscented Toner", category: "Toner", brand: "Klairs", clean: true, price: 22, affiliateUrl: "https://www.amazon.com/dp/B07GD4D22M", tags: { concerns: ["Sensitivity", "Dehydration"], skinTypes: ["Sensitive", "Dry", "Normal"], budgets: ["mid"] }, notes: "Fragrance-free hydration" },
  { name: "Pyunkang Yul Essence Toner", category: "Toner", brand: "Pyunkang Yul", clean: true, price: 18, affiliateUrl: "https://www.amazon.com/dp/B01N0S6M3Q", tags: { concerns: ["Dehydration", "Sensitivity"], skinTypes: ["Dry", "Sensitive", "Normal"], budgets: ["budget", "mid"] }, notes: "Deep hydration" },
  { name: "Etude House SoonJung pH 5.5 Relief Toner", category: "Toner", brand: "Etude House", clean: true, price: 14, affiliateUrl: "https://www.amazon.com/dp/B07B4BQHJT", tags: { concerns: ["Sensitivity", "Redness"], skinTypes: ["Sensitive", "Dry"], budgets: ["budget"] }, notes: "pH-balanced, ultra-gentle" },
  { name: "Caudalie Vinopure Purifying Toner", category: "Toner", brand: "Caudalie", clean: true, price: 28, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Acne", "Large Pores"], skinTypes: ["Oily", "Combination"], budgets: ["mid"], acneTypes: ["comedonal"] }, notes: "Minimizes breakouts" },
  
  // ===== ESSENCES =====
  { name: "COSRX Snail Mucin Essence", category: "Essence", brand: "COSRX", clean: true, price: 22, affiliateUrl: "https://www.amazon.com/dp/B00PBX3L7K", tags: { concerns: ["Fine Lines", "Dehydration", "Dark Spots", "Acne"], skinTypes: ["Normal", "Dry", "Combination", "Oily", "Sensitive"], budgets: ["budget", "mid"], acneTypes: ["inflammatory"] }, notes: "Multi-purpose hydration and healing" },
  { name: "MISSHA Time Revolution The First Treatment Essence", category: "Essence", brand: "MISSHA", clean: true, price: 45, affiliateUrl: "https://www.amazon.com/dp/B07DJCY8Q8", tags: { concerns: ["Dullness", "Fine Lines"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["mid", "luxury"] }, notes: "Fermented essence for glow" },
  { name: "SK-II Facial Treatment Essence", category: "Essence", brand: "SK-II", clean: true, price: 185, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Fine Lines", "Dullness", "Wrinkles"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["luxury"] }, notes: "Iconic anti-aging essence" },
  { name: "Innisfree Green Tea Seed Serum", category: "Essence", brand: "Innisfree", clean: true, price: 27, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dehydration"], skinTypes: ["Normal", "Combination", "Oily"], budgets: ["mid"] }, notes: "Lightweight hydration" },
  
  // ===== VITAMIN C SERUMS =====
  { name: "Naturium Vitamin C Complex Serum", category: "Vitamin C", brand: "Naturium", clean: true, price: 20, affiliateUrl: "https://www.target.com/", tags: { concerns: ["Hyperpigmentation", "Dark Spots", "Dullness"], skinTypes: ["Normal", "Oily", "Combination"], budgets: ["budget", "mid"] }, notes: "Affordable yet effective" },
  { name: "Drunk Elephant C-Firma Vitamin C Serum", category: "Vitamin C", brand: "Drunk Elephant", clean: true, price: 80, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Hyperpigmentation", "Dark Spots", "Fine Lines", "Dullness"], skinTypes: ["Normal", "Oily", "Combination"], budgets: ["luxury"] }, notes: "Potent brightening formula" },
  { name: "Mad Hippie Vitamin C Serum", category: "Vitamin C", brand: "Mad Hippie", clean: true, price: 34, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Hyperpigmentation", "Dark Spots", "Dullness"], skinTypes: ["Normal", "Dry", "Combination", "Sensitive"], budgets: ["mid"] }, notes: "Gentle, stable vitamin C" },
  { name: "Timeless 20% Vitamin C + E Ferulic Acid Serum", category: "Vitamin C", brand: "Timeless", clean: true, price: 24, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Hyperpigmentation", "Dark Spots", "Fine Lines"], skinTypes: ["Normal", "Oily", "Combination"], budgets: ["budget", "mid"] }, notes: "SkinCeuticals dupe" },
  { name: "Melano CC Vitamin C Essence", category: "Vitamin C", brand: "Melano CC", clean: true, price: 16, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dark Spots", "Acne"], skinTypes: ["Normal", "Oily", "Combination"], budgets: ["budget"], acneTypes: ["inflammatory"] }, notes: "Affordable spot treatment" },
  { name: "Klairs Freshly Juiced Vitamin Drop", category: "Vitamin C", brand: "Klairs", clean: true, price: 23, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dullness", "Dark Spots"], skinTypes: ["Sensitive", "Dry", "Normal"], budgets: ["mid"] }, notes: "Gentle for sensitive skin" },
  { name: "Ole Henriksen Truth Serum", category: "Vitamin C", brand: "Ole Henriksen", clean: true, price: 50, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Dullness", "Dark Spots", "Fine Lines"], skinTypes: ["Normal", "Combination"], budgets: ["mid", "luxury"] }, notes: "Brightening and hydrating" },
  { name: "Glow Recipe Pineapple-C Bright Serum", category: "Vitamin C", brand: "Glow Recipe", clean: true, price: 39, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Dullness", "Dark Spots"], skinTypes: ["Normal", "Combination", "Oily"], budgets: ["mid"] }, notes: "Fun texture, brightening" },
  
  // ===== NIACINAMIDE SERUMS =====
  { name: "The Ordinary Niacinamide 10% + Zinc 1%", category: "Niacinamide", brand: "The Ordinary", clean: true, price: 6, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Acne", "Large Pores", "Hyperpigmentation", "Redness"], skinTypes: ["Oily", "Combination", "Normal"], budgets: ["budget"], acneTypes: ["hormonal", "comedonal", "inflammatory"] }, notes: "Affordable, multi-tasking" },
  { name: "Paula's Choice 10% Niacinamide Booster", category: "Niacinamide", brand: "Paula's Choice", clean: true, price: 46, affiliateUrl: "https://www.paulaschoice.com/", tags: { concerns: ["Large Pores", "Uneven Texture", "Hyperpigmentation"], skinTypes: ["Oily", "Combination", "Normal"], budgets: ["mid"] }, notes: "Premium formula" },
  { name: "Good Molecules Niacinamide Serum", category: "Niacinamide", brand: "Good Molecules", clean: true, price: 6, affiliateUrl: "https://www.ulta.com/", tags: { concerns: ["Large Pores", "Acne", "Hyperpigmentation"], skinTypes: ["Oily", "Combination", "Normal"], budgets: ["budget"], acneTypes: ["comedonal"] }, notes: "Budget-friendly option" },
  { name: "The INKEY List Niacinamide", category: "Niacinamide", brand: "The INKEY List", clean: true, price: 8, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Large Pores", "Acne"], skinTypes: ["Oily", "Combination", "Normal"], budgets: ["budget"], acneTypes: ["comedonal"] }, notes: "Simple and effective" },
  { name: "Purito Galacto Niacin 97 Power Essence", category: "Niacinamide", brand: "Purito", clean: true, price: 18, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dullness", "Hyperpigmentation", "Large Pores"], skinTypes: ["Normal", "Combination", "Oily"], budgets: ["budget", "mid"] }, notes: "Fermented, brightening" },
  
  // ===== HYALURONIC ACID =====
  { name: "The Ordinary Hyaluronic Acid 2% + B5", category: "Hyaluronic Acid", brand: "The Ordinary", clean: true, price: 8, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Dehydration", "Fine Lines"], skinTypes: ["Normal", "Dry", "Combination", "Oily", "Sensitive"], budgets: ["budget"] }, notes: "Multi-weight HA" },
  { name: "Vichy Mineral 89", category: "Hyaluronic Acid", brand: "Vichy", clean: true, price: 30, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dehydration", "Fine Lines", "Sensitivity"], skinTypes: ["Normal", "Dry", "Sensitive"], budgets: ["mid"] }, notes: "Mineralizing hydration" },
  { name: "Hada Labo Gokujyun Premium Lotion", category: "Hyaluronic Acid", brand: "Hada Labo", clean: true, price: 14, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dehydration", "Fine Lines"], skinTypes: ["Normal", "Dry", "Combination", "Oily"], budgets: ["budget"] }, notes: "Cult favorite, 5 types of HA" },
  { name: "IUNIK Hyaluronic Acid Serum", category: "Hyaluronic Acid", brand: "IUNIK", clean: true, price: 15, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dehydration"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["budget", "mid"] }, notes: "Lightweight hydration" },
  { name: "Peter Thomas Roth Water Drench Serum", category: "Hyaluronic Acid", brand: "Peter Thomas Roth", clean: true, price: 65, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Dehydration", "Fine Lines"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["luxury"] }, notes: "Cloud cream texture" },
  { name: "Isntree Hyaluronic Acid Water Essence", category: "Hyaluronic Acid", brand: "Isntree", clean: true, price: 16, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dehydration"], skinTypes: ["Normal", "Dry", "Oily", "Combination"], budgets: ["budget", "mid"] }, notes: "Lightweight, absorbs fast" },
  
  // ===== RETINOL & RETINOIDS =====
  { name: "The Ordinary Retinol 0.5% in Squalane", category: "Retinol", brand: "The Ordinary", clean: true, price: 8, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Fine Lines", "Wrinkles", "Uneven Texture", "Acne"], skinTypes: ["Normal", "Oily", "Combination"], budgets: ["budget"], acneTypes: ["comedonal"] }, notes: "Beginner-friendly" },
  { name: "The Ordinary Retinol 1% in Squalane", category: "Retinol", brand: "The Ordinary", clean: true, price: 9, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Fine Lines", "Wrinkles", "Hyperpigmentation"], skinTypes: ["Normal", "Oily", "Combination"], budgets: ["budget"] }, notes: "For experienced users" },
  { name: "Naturium Retinol Complex Serum", category: "Retinol", brand: "Naturium", clean: true, price: 18, affiliateUrl: "https://www.target.com/", tags: { concerns: ["Fine Lines", "Wrinkles", "Uneven Texture"], skinTypes: ["Normal", "Oily", "Combination"], budgets: ["budget", "mid"] }, notes: "Well-formulated, accessible" },
  { name: "Versed Press Restart Retinol Serum", category: "Retinol", brand: "Versed", clean: true, price: 22, affiliateUrl: "https://www.target.com/", tags: { concerns: ["Fine Lines", "Uneven Texture"], skinTypes: ["Normal", "Combination"], budgets: ["mid"] }, notes: "Gentle encapsulated retinol" },
  { name: "CeraVe Resurfacing Retinol Serum", category: "Retinol", brand: "CeraVe", clean: true, price: 18, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dark Spots", "Uneven Texture", "Acne"], skinTypes: ["Normal", "Oily", "Combination"], budgets: ["budget", "mid"], acneTypes: ["comedonal"] }, notes: "Barrier-friendly retinol" },
  { name: "Paula's Choice 1% Retinol Treatment", category: "Retinol", brand: "Paula's Choice", clean: true, price: 58, affiliateUrl: "https://www.paulaschoice.com/", tags: { concerns: ["Fine Lines", "Wrinkles", "Uneven Texture"], skinTypes: ["Normal", "Oily", "Combination"], budgets: ["mid", "luxury"] }, notes: "Premium, well-researched" },
  { name: "The INKEY List Retinol", category: "Retinol", brand: "The INKEY List", clean: true, price: 10, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Fine Lines", "Uneven Texture"], skinTypes: ["Normal", "Combination"], budgets: ["budget"] }, notes: "Affordable starter" },
  { name: "Shani Darden Retinol Reform", category: "Retinol", brand: "Shani Darden", clean: true, price: 88, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Fine Lines", "Wrinkles", "Large Pores"], skinTypes: ["Normal", "Oily", "Combination"], budgets: ["luxury"] }, notes: "Celebrity favorite" },
  { name: "Drunk Elephant A-Passioni Retinol Cream", category: "Retinol", brand: "Drunk Elephant", clean: true, price: 74, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Fine Lines", "Wrinkles"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["luxury"] }, notes: "Vegan retinol" },
  { name: "The Ordinary Granactive Retinoid 2% Emulsion", category: "Retinol", brand: "The Ordinary", clean: true, price: 10, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Fine Lines", "Uneven Texture"], skinTypes: ["Normal", "Sensitive", "Dry"], budgets: ["budget"] }, notes: "Gentler retinoid" },
  
  // ===== TREATMENTS & EXFOLIANTS =====
  { name: "The Ordinary Azelaic Acid 10%", category: "Treatment", brand: "The Ordinary", clean: true, price: 8, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Redness", "Acne", "Hyperpigmentation"], skinTypes: ["Sensitive", "Oily", "Combination", "Normal"], budgets: ["budget"], acneTypes: ["fungal", "inflammatory", "hormonal"] }, notes: "Anti-inflammatory, brightening" },
  { name: "Paula's Choice 2% BHA Liquid Exfoliant", category: "Exfoliant", brand: "Paula's Choice", clean: true, price: 35, affiliateUrl: "https://www.paulaschoice.com/", tags: { concerns: ["Acne", "Large Pores", "Uneven Texture"], skinTypes: ["Oily", "Combination", "Normal"], budgets: ["mid"], acneTypes: ["comedonal", "hormonal"] }, notes: "Gold standard BHA" },
  { name: "COSRX BHA Blackhead Power Liquid", category: "Exfoliant", brand: "COSRX", clean: true, price: 22, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Acne", "Large Pores"], skinTypes: ["Oily", "Combination"], budgets: ["mid"], acneTypes: ["comedonal"] }, notes: "Gentle BHA" },
  { name: "The INKEY List Succinic Acid Treatment", category: "Treatment", brand: "The INKEY List", clean: true, price: 10, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Acne"], skinTypes: ["Oily", "Combination", "Normal"], budgets: ["budget"], acneTypes: ["hormonal", "inflammatory"] }, notes: "Targets hormonal acne" },
  { name: "Naturium Tranexamic Acid 5%", category: "Treatment", brand: "Naturium", clean: true, price: 16, affiliateUrl: "https://www.target.com/", tags: { concerns: ["Hyperpigmentation", "Dark Spots"], skinTypes: ["Normal", "Dry", "Combination", "Oily"], budgets: ["budget", "mid"] }, notes: "Fades discoloration" },
  { name: "The Ordinary Lactic Acid 10% + HA", category: "Exfoliant", brand: "The Ordinary", clean: true, price: 7, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Uneven Texture", "Dullness", "Hyperpigmentation"], skinTypes: ["Normal", "Dry", "Sensitive"], budgets: ["budget"] }, notes: "Gentle AHA" },
  { name: "The Ordinary Glycolic Acid 7% Toning Solution", category: "Exfoliant", brand: "The Ordinary", clean: true, price: 9, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Uneven Texture", "Dullness", "Large Pores"], skinTypes: ["Normal", "Oily", "Combination"], budgets: ["budget"] }, notes: "Daily-use AHA toner" },
  { name: "The Ordinary Mandelic Acid 10% + HA", category: "Exfoliant", brand: "The Ordinary", clean: true, price: 7, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Uneven Texture", "Acne", "Hyperpigmentation"], skinTypes: ["Sensitive", "Normal", "Oily"], budgets: ["budget"], acneTypes: ["comedonal"] }, notes: "Gentlest AHA" },
  { name: "Paula's Choice 10% Azelaic Acid Booster", category: "Treatment", brand: "Paula's Choice", clean: true, price: 40, affiliateUrl: "https://www.paulaschoice.com/", tags: { concerns: ["Redness", "Acne", "Uneven Texture"], skinTypes: ["Sensitive", "Oily", "Combination", "Normal"], budgets: ["mid"], acneTypes: ["fungal", "inflammatory"] }, notes: "Premium azelaic formula" },
  { name: "COSRX AHA 7 Whitehead Power Liquid", category: "Exfoliant", brand: "COSRX", clean: true, price: 22, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dullness", "Uneven Texture"], skinTypes: ["Normal", "Oily", "Combination"], budgets: ["mid"] }, notes: "Gentle glycolic" },
  { name: "Good Molecules Overnight Exfoliating Treatment", category: "Exfoliant", brand: "Good Molecules", clean: true, price: 12, affiliateUrl: "https://www.ulta.com/", tags: { concerns: ["Uneven Texture", "Dullness"], skinTypes: ["Normal", "Combination"], budgets: ["budget"] }, notes: "Affordable night peel" },
  { name: "Drunk Elephant T.L.C. Framboos Glycolic Night Serum", category: "Exfoliant", brand: "Drunk Elephant", clean: true, price: 90, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Uneven Texture", "Dullness", "Large Pores"], skinTypes: ["Normal", "Oily", "Combination"], budgets: ["luxury"] }, notes: "Multi-acid luxury" },
  { name: "Sunday Riley Good Genes Lactic Acid Treatment", category: "Exfoliant", brand: "Sunday Riley", clean: true, price: 85, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Fine Lines", "Hyperpigmentation", "Dullness"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["luxury"] }, notes: "Cult favorite" },
  { name: "Some By Mi AHA BHA PHA 30 Days Miracle Serum", category: "Treatment", brand: "Some By Mi", clean: true, price: 18, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Acne", "Uneven Texture"], skinTypes: ["Oily", "Combination"], budgets: ["budget", "mid"], acneTypes: ["comedonal"] }, notes: "Triple-action exfoliation" },
  { name: "IUNIK Tea Tree Relief Serum", category: "Treatment", brand: "IUNIK", clean: true, price: 17, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Acne", "Redness"], skinTypes: ["Oily", "Combination", "Sensitive"], budgets: ["budget", "mid"], acneTypes: ["inflammatory"] }, notes: "Calms breakouts" },
  { name: "IUNIK Propolis Vitamin Synergy Serum", category: "Serum", brand: "IUNIK", clean: true, price: 18, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dullness", "Acne", "Dehydration"], skinTypes: ["Normal", "Dry", "Combination", "Oily"], budgets: ["budget", "mid"], acneTypes: ["inflammatory"] }, notes: "Nourishing and healing" },
  { name: "IUNIK Beta Glucan Daily Moisture Serum", category: "Serum", brand: "IUNIK", clean: true, price: 16, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dehydration", "Sensitivity"], skinTypes: ["Dry", "Sensitive", "Normal"], budgets: ["budget", "mid"] }, notes: "Ultra-hydrating" },
  { name: "Purito Centella Green Level Buffet Serum", category: "Serum", brand: "Purito", clean: true, price: 19, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Sensitivity", "Redness", "Acne"], skinTypes: ["Sensitive", "Normal", "Combination"], budgets: ["budget", "mid"], acneTypes: ["inflammatory"] }, notes: "Soothing centella" },
  { name: "Krave Beauty Great Barrier Relief", category: "Serum", brand: "Krave Beauty", clean: true, price: 28, affiliateUrl: "https://kravebeauty.com/", tags: { concerns: ["Sensitivity", "Redness", "Dehydration"], skinTypes: ["Sensitive", "Dry", "Normal"], budgets: ["mid"] }, notes: "Barrier repair" },
  { name: "Caudalie Vinopure Blemish Control Serum", category: "Treatment", brand: "Caudalie", clean: true, price: 50, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Acne", "Large Pores"], skinTypes: ["Oily", "Combination"], budgets: ["mid", "luxury"], acneTypes: ["comedonal"] }, notes: "Natural blemish control" },
  { name: "Caudalie Vinoperfect Radiance Serum", category: "Serum", brand: "Caudalie", clean: true, price: 82, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Hyperpigmentation", "Dark Spots", "Dullness"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["luxury"] }, notes: "Brightening bestseller" },
  { name: "The Ordinary Buffet", category: "Serum", brand: "The Ordinary", clean: true, price: 17, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Fine Lines", "Wrinkles", "Dehydration"], skinTypes: ["Normal", "Dry", "Combination", "Oily"], budgets: ["budget"] }, notes: "Multi-peptide formula" },
  { name: "Alpha Arbutin 2% + HA", category: "Treatment", brand: "The Ordinary", clean: true, price: 10, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Hyperpigmentation", "Dark Spots"], skinTypes: ["Normal", "Dry", "Combination", "Oily", "Sensitive"], budgets: ["budget"] }, notes: "Safe brightening" },
  
  // ===== EYE CREAMS =====
  { name: "CeraVe Eye Repair Cream", category: "Eye Cream", brand: "CeraVe", clean: true, price: 15, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dark Circles", "Fine Lines"], skinTypes: ["Normal", "Dry", "Sensitive"], budgets: ["budget"] }, notes: "Gentle, everyday use" },
  { name: "The INKEY List Caffeine Eye Cream", category: "Eye Cream", brand: "The INKEY List", clean: true, price: 10, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Dark Circles", "Dehydration"], skinTypes: ["Normal", "Dry", "Oily", "Combination"], budgets: ["budget"] }, notes: "Depuffs and brightens" },
  { name: "Naturium Multi-Peptide Eye Cream", category: "Eye Cream", brand: "Naturium", clean: true, price: 16, affiliateUrl: "https://www.target.com/", tags: { concerns: ["Fine Lines", "Dark Circles"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["budget", "mid"] }, notes: "Anti-aging eye care" },
  { name: "The Ordinary Caffeine Solution 5% + EGCG", category: "Eye Cream", brand: "The Ordinary", clean: true, price: 7, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Dark Circles"], skinTypes: ["Normal", "Oily", "Combination"], budgets: ["budget"] }, notes: "Reduces puffiness" },
  { name: "Kiehl's Creamy Eye Treatment with Avocado", category: "Eye Cream", brand: "Kiehl's", clean: true, price: 52, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Dehydration", "Fine Lines"], skinTypes: ["Dry", "Normal"], budgets: ["mid", "luxury"] }, notes: "Hydrating classic" },
  { name: "Glow Recipe Avocado Melt Retinol Eye Cream", category: "Eye Cream", brand: "Glow Recipe", clean: true, price: 42, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Fine Lines", "Dark Circles"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["mid"] }, notes: "Gentle retinol for eyes" },
  { name: "Youth To The People Superberry Hydrate + Glow Dream Eye Cream", category: "Eye Cream", brand: "Youth To The People", clean: true, price: 48, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Dark Circles", "Dullness"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["mid", "luxury"] }, notes: "Brightening and hydrating" },
  { name: "Good Molecules Caffeine Energizing Eye Cream", category: "Eye Cream", brand: "Good Molecules", clean: true, price: 10, affiliateUrl: "https://www.ulta.com/", tags: { concerns: ["Dark Circles", "Dehydration"], skinTypes: ["Normal", "Dry", "Oily", "Combination"], budgets: ["budget"] }, notes: "Affordable depuffer" },
  { name: "Innisfree Green Tea Seed Eye Cream", category: "Eye Cream", brand: "Innisfree", clean: true, price: 25, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dehydration", "Fine Lines"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["mid"] }, notes: "Lightweight hydration" },
  
  // ===== MOISTURIZERS =====
  { name: "CeraVe Moisturizing Cream", category: "Moisturizer", brand: "CeraVe", clean: true, price: 16, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dehydration", "Sensitivity"], skinTypes: ["Dry", "Normal", "Sensitive"], budgets: ["budget"] }, notes: "Holy grail moisturizer" },
  { name: "La Roche-Posay Cicaplast Baume B5", category: "Moisturizer", brand: "La Roche-Posay", clean: true, price: 17, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Redness", "Sensitivity", "Dehydration"], skinTypes: ["Dry", "Sensitive", "Normal"], budgets: ["budget"] }, notes: "Barrier repair" },
  { name: "Versed Dew Point Moisturizer", category: "Moisturizer", brand: "Versed", clean: true, price: 18, affiliateUrl: "https://www.target.com/", tags: { concerns: ["Dehydration"], skinTypes: ["Oily", "Combination", "Normal"], budgets: ["budget", "mid"] }, notes: "Lightweight gel-cream" },
  { name: "Neutrogena Hydro Boost Water Gel", category: "Moisturizer", brand: "Neutrogena", clean: true, price: 19, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dehydration"], skinTypes: ["Oily", "Combination", "Normal"], budgets: ["budget"] }, notes: "Oil-free hydration" },
  { name: "Vanicream Moisturizing Cream", category: "Moisturizer", brand: "Vanicream", clean: true, price: 14, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Sensitivity", "Dehydration"], skinTypes: ["Sensitive", "Dry", "Normal"], budgets: ["budget"] }, notes: "Ultra-gentle" },
  { name: "First Aid Beauty Ultra Repair Cream", category: "Moisturizer", brand: "First Aid Beauty", clean: true, price: 38, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Dehydration", "Sensitivity", "Redness"], skinTypes: ["Dry", "Sensitive", "Normal"], budgets: ["mid"] }, notes: "Intensive repair" },
  { name: "Youth To The People Adaptogen Cream", category: "Moisturizer", brand: "Youth To The People", clean: true, price: 58, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Dehydration", "Dullness"], skinTypes: ["Normal", "Combination", "Dry"], budgets: ["mid", "luxury"] }, notes: "Stress-defense" },
  { name: "Naturium Multi-Peptide Moisturizer", category: "Moisturizer", brand: "Naturium", clean: true, price: 20, affiliateUrl: "https://www.target.com/", tags: { concerns: ["Fine Lines", "Dehydration"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["budget", "mid"] }, notes: "Anti-aging daily cream" },
  { name: "COSRX Advanced Snail 92 All in One Cream", category: "Moisturizer", brand: "COSRX", clean: true, price: 22, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Fine Lines", "Dehydration", "Acne"], skinTypes: ["Normal", "Dry", "Combination", "Oily"], budgets: ["budget", "mid"], acneTypes: ["inflammatory"] }, notes: "Healing and hydrating" },
  { name: "Purito Oat-in Calming Gel Cream", category: "Moisturizer", brand: "Purito", clean: true, price: 17, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Sensitivity", "Redness"], skinTypes: ["Sensitive", "Normal", "Combination"], budgets: ["budget", "mid"] }, notes: "Soothing gel-cream" },
  { name: "Klairs Rich Moist Soothing Cream", category: "Moisturizer", brand: "Klairs", clean: true, price: 26, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Sensitivity", "Dehydration"], skinTypes: ["Sensitive", "Dry", "Normal"], budgets: ["mid"] }, notes: "Calming hydration" },
  { name: "Etude House SoonJung 2x Barrier Intensive Cream", category: "Moisturizer", brand: "Etude House", clean: true, price: 18, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Sensitivity", "Redness"], skinTypes: ["Sensitive", "Dry"], budgets: ["budget", "mid"] }, notes: "Barrier-focused" },
  { name: "Belif The True Cream Aqua Bomb", category: "Moisturizer", brand: "Belif", clean: true, price: 42, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Dehydration"], skinTypes: ["Oily", "Combination", "Normal"], budgets: ["mid"] }, notes: "Lightweight burst" },
  { name: "Laneige Water Sleeping Mask", category: "Moisturizer", brand: "Laneige", clean: true, price: 32, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Dehydration", "Dullness"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["mid"] }, notes: "Overnight hydration" },
  { name: "Drunk Elephant Protini Polypeptide Cream", category: "Moisturizer", brand: "Drunk Elephant", clean: true, price: 68, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Fine Lines", "Wrinkles", "Dehydration"], skinTypes: ["Normal", "Dry", "Combination", "Oily"], budgets: ["luxury"] }, notes: "Protein-rich anti-aging" },
  { name: "Drunk Elephant Lala Retro Whipped Cream", category: "Moisturizer", brand: "Drunk Elephant", clean: true, price: 60, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Dehydration", "Fine Lines"], skinTypes: ["Dry", "Normal"], budgets: ["luxury"] }, notes: "Rich night cream" },
  { name: "Krave Beauty Oat So Simple Water Cream", category: "Moisturizer", brand: "Krave Beauty", clean: true, price: 28, affiliateUrl: "https://kravebeauty.com/", tags: { concerns: ["Sensitivity"], skinTypes: ["Normal", "Combination", "Oily", "Sensitive"], budgets: ["mid"] }, notes: "Minimal ingredients" },
  { name: "Tatcha The Water Cream", category: "Moisturizer", brand: "Tatcha", clean: true, price: 72, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Large Pores", "Dullness"], skinTypes: ["Oily", "Combination", "Normal"], budgets: ["luxury"] }, notes: "Oil-free luxury" },
  { name: "Tatcha The Dewy Skin Cream", category: "Moisturizer", brand: "Tatcha", clean: true, price: 72, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Dehydration", "Dullness"], skinTypes: ["Dry", "Normal"], budgets: ["luxury"] }, notes: "Plumping moisture" },
  { name: "Herbivore Pink Cloud Rosewater Moisture Cream", category: "Moisturizer", brand: "Herbivore", clean: true, price: 48, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Dehydration", "Redness"], skinTypes: ["Dry", "Normal", "Sensitive"], budgets: ["mid", "luxury"] }, notes: "Soft, rosewater-based" },
  { name: "Glow Recipe Plum Plump Hyaluronic Cream", category: "Moisturizer", brand: "Glow Recipe", clean: true, price: 42, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Dehydration", "Fine Lines"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["mid"] }, notes: "Bouncy hydration" },
  { name: "The Ordinary Natural Moisturizing Factors + HA", category: "Moisturizer", brand: "The Ordinary", clean: true, price: 8, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Dehydration"], skinTypes: ["Normal", "Dry", "Oily", "Combination"], budgets: ["budget"] }, notes: "Simple, effective" },
  { name: "Purito Deep Sea Pure Water Cream", category: "Moisturizer", brand: "Purito", clean: true, price: 19, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dehydration"], skinTypes: ["Oily", "Combination", "Normal"], budgets: ["budget", "mid"] }, notes: "Lightweight gel" },
  { name: "Purito Dermide Cica Barrier Sleeping Pack", category: "Moisturizer", brand: "Purito", clean: true, price: 22, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Sensitivity", "Redness", "Dehydration"], skinTypes: ["Sensitive", "Dry", "Normal"], budgets: ["mid"] }, notes: "Overnight barrier repair" },
  { name: "Caudalie Vinosource Moisturizing Sorbet", category: "Moisturizer", brand: "Caudalie", clean: true, price: 42, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Dehydration"], skinTypes: ["Normal", "Combination"], budgets: ["mid"] }, notes: "Lightweight sorbet" },
  { name: "Fresh Lotus Youth Preserve Face Cream", category: "Moisturizer", brand: "Fresh", clean: true, price: 50, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Fine Lines", "Dullness"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["mid", "luxury"] }, notes: "Antioxidant-rich" },
  
  // ===== FACE OILS =====
  { name: "The Ordinary 100% Plant-Derived Squalane", category: "Face Oil", brand: "The Ordinary", clean: true, price: 8, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Dehydration", "Fine Lines"], skinTypes: ["Dry", "Normal", "Sensitive"], budgets: ["budget"] }, notes: "Lightweight, non-comedogenic" },
  { name: "The Ordinary 100% Organic Cold-Pressed Rose Hip Seed Oil", category: "Face Oil", brand: "The Ordinary", clean: true, price: 10, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Hyperpigmentation", "Fine Lines", "Dehydration"], skinTypes: ["Dry", "Normal", "Combination"], budgets: ["budget"] }, notes: "Regenerating oil" },
  { name: "Versed Sunday Morning Antioxidant Oil", category: "Face Oil", brand: "Versed", clean: true, price: 22, affiliateUrl: "https://www.target.com/", tags: { concerns: ["Dullness", "Dehydration"], skinTypes: ["Dry", "Normal"], budgets: ["mid"] }, notes: "Nourishing blend" },
  { name: "Biossance Squalane + Vitamin C Rose Oil", category: "Face Oil", brand: "Biossance", clean: true, price: 72, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Dullness", "Hyperpigmentation"], skinTypes: ["Dry", "Normal", "Combination"], budgets: ["luxury"] }, notes: "Brightening oil" },
  { name: "Drunk Elephant Virgin Marula Luxury Facial Oil", category: "Face Oil", brand: "Drunk Elephant", clean: true, price: 40, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Dehydration", "Fine Lines"], skinTypes: ["Dry", "Normal"], budgets: ["mid", "luxury"] }, notes: "Rich, nourishing" },
  { name: "Herbivore Lapis Facial Oil", category: "Face Oil", brand: "Herbivore", clean: true, price: 72, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Acne", "Redness"], skinTypes: ["Oily", "Combination"], budgets: ["luxury"], acneTypes: ["inflammatory"] }, notes: "Balancing blue tansy" },
  { name: "Sunday Riley UFO Ultra-Clarifying Face Oil", category: "Face Oil", brand: "Sunday Riley", clean: true, price: 80, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Acne", "Large Pores"], skinTypes: ["Oily", "Combination"], budgets: ["luxury"], acneTypes: ["comedonal"] }, notes: "Acne-fighting oil" },
  { name: "Sunday Riley C.E.O. Glow Vitamin C + Turmeric Face Oil", category: "Face Oil", brand: "Sunday Riley", clean: true, price: 40, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Dullness", "Dark Spots"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["mid", "luxury"] }, notes: "Brightening glow" },
  { name: "COSRX Full Fit Propolis Light Ampoule", category: "Face Oil", brand: "COSRX", clean: true, price: 25, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dullness", "Dehydration"], skinTypes: ["Normal", "Dry", "Combination", "Oily"], budgets: ["mid"] }, notes: "Healing propolis" },
  { name: "Cocokind Chia Facial Oil", category: "Face Oil", brand: "Cocokind", clean: true, price: 14, affiliateUrl: "https://www.ulta.com/", tags: { concerns: ["Dehydration"], skinTypes: ["Dry", "Normal"], budgets: ["budget"] }, notes: "Omega-rich" },
  
  // ===== SUNSCREENS =====
  { name: "EltaMD UV Clear SPF 46", category: "Sunscreen", brand: "EltaMD", clean: true, price: 41, affiliateUrl: "https://www.dermstore.com/", tags: { concerns: ["Acne", "Redness", "Sensitivity"], skinTypes: ["Oily", "Combination", "Normal", "Sensitive"], budgets: ["mid"], acneTypes: ["inflammatory", "hormonal", "comedonal"] }, notes: "Dermatologist favorite" },
  { name: "La Roche-Posay Anthelios SPF 50", category: "Sunscreen", brand: "La Roche-Posay", clean: true, price: 36, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Sensitivity"], skinTypes: ["Normal", "Dry", "Combination", "Oily", "Sensitive"], budgets: ["mid"] }, notes: "High protection" },
  { name: "La Roche-Posay Anthelios Mineral SPF 50", category: "Sunscreen", brand: "La Roche-Posay", clean: true, price: 35, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Sensitivity", "Redness"], skinTypes: ["Sensitive", "Dry", "Normal"], budgets: ["mid"] }, notes: "Mineral, gentle" },
  { name: "Supergoop! Unseen Sunscreen SPF 40", category: "Sunscreen", brand: "Supergoop!", clean: true, price: 38, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Large Pores"], skinTypes: ["Oily", "Combination", "Normal"], budgets: ["mid"] }, notes: "Invisible, primer-like" },
  { name: "COSRX Aloe Soothing Sun Cream SPF 50", category: "Sunscreen", brand: "COSRX", clean: true, price: 16, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Sensitivity"], skinTypes: ["Normal", "Dry", "Sensitive"], budgets: ["budget"] }, notes: "Calming, hydrating" },
  { name: "Beauty of Joseon Relief Sun SPF 50+", category: "Sunscreen", brand: "Beauty of Joseon", clean: true, price: 18, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dehydration"], skinTypes: ["Normal", "Dry", "Combination", "Oily"], budgets: ["budget"] }, notes: "Rice bran, lightweight" },
  { name: "Purito Centella Green Level Unscented Sun SPF 50+", category: "Sunscreen", brand: "Purito", clean: true, price: 16, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Sensitivity", "Redness"], skinTypes: ["Sensitive", "Normal", "Dry"], budgets: ["budget"] }, notes: "Centella, fragrance-free" },
  { name: "Canmake Mermaid Skin Gel UV SPF 50+", category: "Sunscreen", brand: "Canmake", clean: true, price: 15, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dehydration"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["budget"] }, notes: "Dewy finish" },
  { name: "Isntree Hyaluronic Acid Watery Sun Gel SPF 50+", category: "Sunscreen", brand: "Isntree", clean: true, price: 18, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dehydration"], skinTypes: ["Normal", "Oily", "Combination"], budgets: ["budget"] }, notes: "Lightweight, hydrating" },
  { name: "Round Lab Birch Juice Moisturizing Sunscreen SPF 50+", category: "Sunscreen", brand: "Round Lab", clean: true, price: 20, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dehydration"], skinTypes: ["Dry", "Normal", "Sensitive"], budgets: ["budget", "mid"] }, notes: "Hydrating, no white cast" },
  { name: "Krave Beauty Beet The Sun SPF 50+", category: "Sunscreen", brand: "Krave Beauty", clean: true, price: 22, affiliateUrl: "https://kravebeauty.com/", tags: { concerns: ["Dullness"], skinTypes: ["Normal", "Combination", "Oily"], budgets: ["mid"] }, notes: "Antioxidant-rich" },
  { name: "Biore UV Aqua Rich Watery Essence SPF 50+", category: "Sunscreen", brand: "Biore", clean: true, price: 15, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Large Pores"], skinTypes: ["Oily", "Combination", "Normal"], budgets: ["budget"] }, notes: "Japanese cult favorite" },
  { name: "Skin Aqua Super Moisture Milk SPF 50+", category: "Sunscreen", brand: "Skin Aqua", clean: true, price: 14, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dehydration"], skinTypes: ["Normal", "Oily", "Combination"], budgets: ["budget"] }, notes: "Lightweight, no white cast" },
  
  // ===== MASKS =====
  { name: "Innisfree Volcanic Pore Clay Mask", category: "Mask", brand: "Innisfree", clean: true, price: 15, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Large Pores", "Acne"], skinTypes: ["Oily", "Combination"], budgets: ["budget"], acneTypes: ["comedonal"] }, notes: "Deep pore cleansing" },
  { name: "Glow Recipe Watermelon Glow Sleeping Mask", category: "Mask", brand: "Glow Recipe", clean: true, price: 45, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Dehydration", "Dullness"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["mid"] }, notes: "Overnight hydration" },
  { name: "Summer Fridays Jet Lag Mask", category: "Mask", brand: "Summer Fridays", clean: true, price: 52, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Dehydration", "Dullness"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["mid", "luxury"] }, notes: "Instant hydration" },
  { name: "Origins Clear Improvement Charcoal Mask", category: "Mask", brand: "Origins", clean: true, price: 28, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Acne", "Large Pores"], skinTypes: ["Oily", "Combination"], budgets: ["mid"], acneTypes: ["comedonal"] }, notes: "Detoxifying" },

  // ===== K-BEAUTY EXPANSION =====
  // Cleansers
  { name: "Beauty of Joseon Ginseng Cleansing Oil", category: "Double Cleanser", brand: "Beauty of Joseon", clean: true, price: 16, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dullness", "Dehydration"], skinTypes: ["Dry", "Normal", "Combination"], budgets: ["budget"] }, notes: "Nourishing first cleanse with traditional Korean ginseng" },
  { name: "Haruharu Wonder Black Rice Hyaluronic Toner", category: "Toner", brand: "Haruharu Wonder", clean: true, price: 19, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dehydration", "Dullness"], skinTypes: ["Dry", "Normal", "Sensitive"], budgets: ["budget", "mid"] }, notes: "Antioxidant-rich hydrating toner" },
  { name: "Mixsoon Bean Essence", category: "Essence", brand: "Mixsoon", clean: true, price: 28, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dullness", "Fine Lines", "Dehydration"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["mid"] }, notes: "Fermented soybean brightening essence" },
  { name: "Thank You Farmer Back To Iceland Cream", category: "Moisturizer", brand: "Thank You Farmer", clean: true, price: 28, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dehydration", "Sensitivity"], skinTypes: ["Dry", "Normal", "Sensitive"], budgets: ["mid"] }, notes: "Arctic mineral hydration" },
  { name: "Anua Heartleaf 77% Soothing Toner", category: "Toner", brand: "Anua", clean: true, price: 21, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Redness", "Sensitivity", "Acne"], skinTypes: ["Sensitive", "Normal", "Combination"], budgets: ["budget", "mid"], acneTypes: ["inflammatory"] }, notes: "High-concentration heartleaf calming toner" },
  { name: "Anua Heartleaf Pore Control Cleansing Oil", category: "Double Cleanser", brand: "Anua", clean: true, price: 22, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Large Pores", "Acne"], skinTypes: ["Oily", "Combination", "Normal"], budgets: ["budget", "mid"], acneTypes: ["comedonal"] }, notes: "Pore-clarifying cleansing oil" },
  { name: "Round Lab 1025 Dokdo Toner", category: "Toner", brand: "Round Lab", clean: true, price: 18, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dehydration", "Sensitivity"], skinTypes: ["Normal", "Dry", "Sensitive"], budgets: ["budget"] }, notes: "Mineral-rich ocean water toner" },
  { name: "By Wishtrend Vitamin 75 Maximizing Cream", category: "Moisturizer", brand: "By Wishtrend", clean: true, price: 30, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dullness", "Fine Lines", "Dehydration"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["mid"] }, notes: "Vitamin-packed brightening cream" },
  { name: "Skin1004 Madagascar Centella Ampoule", category: "Serum", brand: "Skin1004", clean: true, price: 16, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Redness", "Sensitivity", "Acne"], skinTypes: ["Sensitive", "Normal", "Combination", "Oily"], budgets: ["budget"], acneTypes: ["inflammatory"] }, notes: "Pure centella calming ampoule" },
  { name: "Dr. Jart+ Cicapair Tiger Grass Cream", category: "Moisturizer", brand: "Dr. Jart+", clean: true, price: 52, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Redness", "Sensitivity"], skinTypes: ["Sensitive", "Normal", "Combination"], budgets: ["mid"] }, notes: "Color-correcting barrier repair cream" },
  { name: "SOME BY MI Yuja Niacin Brightening Moisture Gel Cream", category: "Moisturizer", brand: "Some By Mi", clean: true, price: 20, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dullness", "Hyperpigmentation", "Dehydration"], skinTypes: ["Normal", "Oily", "Combination"], budgets: ["budget", "mid"] }, notes: "Brightening yuzu gel cream" },
  { name: "Tonymoly Master Lab Hyaluronic Acid Mask", category: "Mask", brand: "Tonymoly", clean: true, price: 4, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dehydration", "Fine Lines"], skinTypes: ["Normal", "Dry", "Combination", "Oily", "Sensitive"], budgets: ["budget"] }, notes: "Intensive sheet mask hydration" },
  { name: "Manyo Factory Galactomyces Niacin Special Treatment Essence", category: "Essence", brand: "Manyo Factory", clean: true, price: 35, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Large Pores", "Dullness", "Uneven Texture"], skinTypes: ["Oily", "Combination", "Normal"], budgets: ["mid"] }, notes: "Fermented brightening essence" },
  { name: "Cosrx Propolis Light Ampule", category: "Serum", brand: "COSRX", clean: true, price: 24, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dullness", "Dehydration", "Acne"], skinTypes: ["Normal", "Dry", "Combination", "Oily"], budgets: ["mid"], acneTypes: ["inflammatory"] }, notes: "83% black bee propolis healing ampoule" },
  { name: "Papa Recipe Bombee Honey Mask", category: "Mask", brand: "Papa Recipe", clean: true, price: 25, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dehydration", "Dullness"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["mid"] }, notes: "Cult honey hydration mask" },

  // ===== CANADIAN & INTERNATIONAL BRANDS =====
  { name: "Consonant Hydrextreme", category: "Moisturizer", brand: "Consonant", clean: true, price: 48, affiliateUrl: "https://www.consonantskincare.com/", tags: { concerns: ["Dehydration", "Fine Lines", "Sensitivity"], skinTypes: ["Dry", "Normal", "Sensitive"], budgets: ["mid"] }, notes: "Canadian clean beauty, intense hydration" },
  { name: "Consonant The Perfect Sunscreen SPF 30", category: "Sunscreen", brand: "Consonant", clean: true, price: 38, affiliateUrl: "https://www.consonantskincare.com/", tags: { concerns: ["Sensitivity"], skinTypes: ["Normal", "Sensitive", "Dry", "Combination"], budgets: ["mid"] }, notes: "Canadian-made mineral sunscreen, reef-safe" },
  { name: "Skin Essence Organics Vitamin C Serum", category: "Vitamin C", brand: "Skin Essence Organics", clean: true, price: 42, affiliateUrl: "https://skinessence.ca/", tags: { concerns: ["Dullness", "Dark Spots", "Hyperpigmentation"], skinTypes: ["Normal", "Dry", "Sensitive"], budgets: ["mid"] }, notes: "Canadian-certified organic vitamin C" },
  { name: "Annmarie Gianni Anti-Aging Serum", category: "Serum", brand: "Annmarie Gianni", clean: true, price: 64, affiliateUrl: "https://www.annmariegianni.com/", tags: { concerns: ["Fine Lines", "Wrinkles", "Dullness"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["luxury"] }, notes: "Wild-crafted botanical anti-aging" },
  { name: "The Ordinary (DECIEM) Marine Hyaluronics", category: "Hyaluronic Acid", brand: "The Ordinary", clean: true, price: 9, affiliateUrl: "https://deciem.com/", tags: { concerns: ["Dehydration"], skinTypes: ["Normal", "Oily", "Combination", "Dry"], budgets: ["budget"] }, notes: "Canadian brand DECIEM; ultra-lightweight hydration" },
  { name: "Bioderma Sensibio H2O Micellar Water", category: "Cleanser", brand: "Bioderma", clean: true, price: 15, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Sensitivity", "Redness"], skinTypes: ["Sensitive", "Normal", "Dry"], budgets: ["budget"] }, notes: "French pharmacy icon, ultra-gentle micellar" },
  { name: "Avène Tolerance Control Soothing Skin Recovery Balm", category: "Moisturizer", brand: "Avène", clean: true, price: 38, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Sensitivity", "Redness", "Dehydration"], skinTypes: ["Sensitive", "Dry", "Normal"], budgets: ["mid"] }, notes: "French thermal spring water for ultra-reactive skin" },
  { name: "Nuxe Huile Prodigieuse Multi-Purpose Dry Oil", category: "Face Oil", brand: "Nuxe", clean: true, price: 48, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Dehydration", "Dullness"], skinTypes: ["Dry", "Normal"], budgets: ["mid"] }, notes: "French cult face & body oil" },
  { name: "REN Clean Skincare Evercalm Global Protection Day Cream", category: "Moisturizer", brand: "REN Clean Skincare", clean: true, price: 58, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Sensitivity", "Redness", "Dehydration"], skinTypes: ["Sensitive", "Dry", "Normal"], budgets: ["mid", "luxury"] }, notes: "UK-based clean beauty barrier cream" },
  { name: "Emma Hardie Amazing Face Cleansing Balm", category: "Double Cleanser", brand: "Emma Hardie", clean: true, price: 62, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Dullness", "Dehydration"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["luxury"] }, notes: "UK luxury cleansing balm with massage tool" },
  { name: "Medik8 Crystal Retinal 3", category: "Retinol", brand: "Medik8", clean: true, price: 55, affiliateUrl: "https://www.medik8.com/", tags: { concerns: ["Fine Lines", "Wrinkles", "Uneven Texture"], skinTypes: ["Normal", "Combination", "Oily"], budgets: ["mid", "luxury"] }, notes: "Australian-developed retinaldehyde (faster than retinol)" },
  { name: "Alpha-H Liquid Gold", category: "Exfoliant", brand: "Alpha-H", clean: true, price: 60, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Uneven Texture", "Dullness", "Fine Lines"], skinTypes: ["Normal", "Oily", "Combination"], budgets: ["mid", "luxury"] }, notes: "Australian cult glycolic acid treatment" },
  { name: "Mukti Organics Rose Hip & Peptide Moisturiser", category: "Moisturizer", brand: "Mukti Organics", clean: true, price: 72, affiliateUrl: "https://www.muktibotanicals.com/", tags: { concerns: ["Fine Lines", "Dehydration", "Dullness"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["luxury"] }, notes: "Australian certified-organic peptide moisturizer" },

  // ===== LUXURY EXPANSION =====
  { name: "La Mer Crème de la Mer", category: "Moisturizer", brand: "La Mer", clean: false, price: 195, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Dehydration", "Fine Lines", "Sensitivity"], skinTypes: ["Dry", "Normal", "Sensitive"], budgets: ["luxury"] }, notes: "Iconic luxury moisturizer with Miracle Broth" },
  { name: "La Mer The Concentrate", category: "Serum", brand: "La Mer", clean: false, price: 395, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Fine Lines", "Redness", "Sensitivity"], skinTypes: ["Dry", "Normal", "Sensitive"], budgets: ["luxury"] }, notes: "Ultra-luxury barrier-repairing concentrate" },
  { name: "Sisley Black Rose Cream Mask", category: "Mask", brand: "Sisley", clean: false, price: 145, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Dullness", "Fine Lines", "Dehydration"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["luxury"] }, notes: "French luxury anti-aging mask" },
  { name: "Charlotte Tilbury Magic Cream", category: "Moisturizer", brand: "Charlotte Tilbury", clean: false, price: 100, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Fine Lines", "Dehydration", "Dullness"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["luxury"] }, notes: "Celebrity makeup artist formula" },
  { name: "Augustinus Bader The Cream", category: "Moisturizer", brand: "Augustinus Bader", clean: true, price: 280, affiliateUrl: "https://www.net-a-porter.com/", tags: { concerns: ["Fine Lines", "Wrinkles", "Dehydration"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["luxury"] }, notes: "Science-led stem cell activation cream" },
  { name: "Augustinus Bader The Rich Cream", category: "Moisturizer", brand: "Augustinus Bader", clean: true, price: 295, affiliateUrl: "https://www.net-a-porter.com/", tags: { concerns: ["Fine Lines", "Wrinkles", "Dehydration"], skinTypes: ["Dry", "Sensitive"], budgets: ["luxury"] }, notes: "Richest version of the TFC8 formula" },
  { name: "Valmont Hydra3 Regenetic Cream", category: "Moisturizer", brand: "Valmont", clean: false, price: 310, affiliateUrl: "https://www.valmontcosmetics.com/", tags: { concerns: ["Fine Lines", "Wrinkles", "Dehydration"], skinTypes: ["Dry", "Normal"], budgets: ["luxury"] }, notes: "Swiss luxury cellular repair cream" },
  { name: "Clé de Peau Beauté Intensive Eye Contour Cream", category: "Eye Cream", brand: "Clé de Peau Beauté", clean: false, price: 215, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Dark Circles", "Fine Lines"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["luxury"] }, notes: "Ultra-luxury Japanese eye cream" },
  { name: "Tata Harper Resurfacing Serum", category: "Exfoliant", brand: "Tata Harper", clean: true, price: 158, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Uneven Texture", "Dullness", "Fine Lines"], skinTypes: ["Normal", "Combination", "Oily"], budgets: ["luxury"] }, notes: "Farm-to-face luxury AHA serum" },
  { name: "Vintner's Daughter Active Botanical Serum", category: "Serum", brand: "Vintner's Daughter", clean: true, price: 195, affiliateUrl: "https://www.vintnersdaughter.com/", tags: { concerns: ["Fine Lines", "Dullness", "Dehydration", "Redness"], skinTypes: ["Normal", "Dry", "Combination", "Sensitive"], budgets: ["luxury"] }, notes: "Cult multi-botanical luxury serum" },
  { name: "NARS Luminous Moisture Cream", category: "Moisturizer", brand: "NARS", clean: false, price: 82, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Dehydration", "Dullness"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["luxury"] }, notes: "Luminizing luxury moisturizer" },
  { name: "Shiseido Ultimune Power Infusing Concentrate", category: "Serum", brand: "Shiseido", clean: false, price: 95, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Fine Lines", "Dullness", "Sensitivity"], skinTypes: ["Normal", "Dry", "Combination", "Sensitive"], budgets: ["luxury"] }, notes: "Immune-boosting Japanese power serum" },
  { name: "Sulwhasoo First Care Activating Serum", category: "Essence", brand: "Sulwhasoo", clean: false, price: 95, affiliateUrl: "https://www.sephora.com/", tags: { concerns: ["Fine Lines", "Dullness", "Dehydration"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["luxury"] }, notes: "K-luxury Korean herbal essence" },
  { name: "La Prairie Skin Caviar Luxe Cream", category: "Moisturizer", brand: "La Prairie", clean: false, price: 440, affiliateUrl: "https://www.laprairie.com/", tags: { concerns: ["Fine Lines", "Wrinkles", "Dehydration"], skinTypes: ["Dry", "Normal"], budgets: ["luxury"] }, notes: "Ultra-luxury Swiss caviar moisturizer" },

  // ===== DRUGSTORE / BUDGET EXPANSION =====
  { name: "e.l.f. Holy Hydration Face Cream", category: "Moisturizer", brand: "e.l.f.", clean: true, price: 12, affiliateUrl: "https://www.elfcosmetics.com/", tags: { concerns: ["Dehydration"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["budget"] }, notes: "Drugstore dupe for luxury hyaluronic creams" },
  { name: "Cetaphil Gentle Skin Cleanser", category: "Cleanser", brand: "Cetaphil", clean: true, price: 10, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Sensitivity", "Redness", "Dehydration"], skinTypes: ["Sensitive", "Dry", "Normal"], budgets: ["budget"] }, notes: "Dermatologist staple, ultra-gentle" },
  { name: "Cetaphil Moisturizing Lotion", category: "Moisturizer", brand: "Cetaphil", clean: true, price: 12, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dehydration", "Sensitivity"], skinTypes: ["Sensitive", "Dry", "Normal"], budgets: ["budget"] }, notes: "Fragrance-free classic moisturizer" },
  { name: "Olay Regenerist Micro-Sculpting Cream", category: "Moisturizer", brand: "Olay", clean: false, price: 25, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Fine Lines", "Wrinkles", "Dehydration"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["budget"] }, notes: "Drugstore anti-aging powerhouse" },
  { name: "RoC Retinol Correxion Line Smoothing Serum", category: "Retinol", brand: "RoC", clean: false, price: 24, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Fine Lines", "Wrinkles", "Uneven Texture"], skinTypes: ["Normal", "Combination", "Oily"], budgets: ["budget"] }, notes: "Affordable drugstore retinol" },
  { name: "Differin Adapalene Gel 0.1%", category: "Retinol", brand: "Differin", clean: true, price: 15, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Acne", "Uneven Texture", "Large Pores"], skinTypes: ["Oily", "Combination", "Normal"], budgets: ["budget"], acneTypes: ["comedonal", "inflammatory", "hormonal"] }, notes: "OTC retinoid, clinically proven for acne" },
  { name: "Neutrogena Rapid Tone Repair Vitamin C Serum", category: "Vitamin C", brand: "Neutrogena", clean: false, price: 22, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dark Spots", "Dullness"], skinTypes: ["Normal", "Combination", "Oily"], budgets: ["budget"] }, notes: "Drugstore brightening serum" },
  { name: "L'Oréal Revitalift 1.5% Pure Hyaluronic Acid Serum", category: "Hyaluronic Acid", brand: "L'Oréal", clean: false, price: 20, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Fine Lines", "Dehydration"], skinTypes: ["Normal", "Dry", "Combination", "Oily"], budgets: ["budget"] }, notes: "High-concentration drugstore HA" },
  { name: "Pond's Rejuveness Anti-Wrinkle Cream", category: "Moisturizer", brand: "Pond's", clean: false, price: 8, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Fine Lines", "Wrinkles", "Dehydration"], skinTypes: ["Normal", "Dry"], budgets: ["budget"] }, notes: "Ultra-affordable anti-aging classic" },
  { name: "Aveeno Calm + Restore Triple Oat Serum", category: "Serum", brand: "Aveeno", clean: true, price: 22, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Sensitivity", "Redness", "Dehydration"], skinTypes: ["Sensitive", "Dry", "Normal"], budgets: ["budget"] }, notes: "Colloidal oat soothing serum" },
  { name: "Clean & Clear Morning Burst Facial Cleanser", category: "Cleanser", brand: "Clean & Clear", clean: false, price: 6, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Acne", "Large Pores"], skinTypes: ["Oily", "Combination"], budgets: ["budget"], acneTypes: ["comedonal"] }, notes: "Budget brightening gel wash" },
  { name: "Nivea Soft Moisturizing Cream", category: "Moisturizer", brand: "Nivea", clean: false, price: 7, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Dehydration"], skinTypes: ["Normal", "Dry", "Combination"], budgets: ["budget"] }, notes: "Affordable international classic" },
  { name: "Simple Kind to Skin Moisturising Facial Wash", category: "Cleanser", brand: "Simple", clean: true, price: 8, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Sensitivity"], skinTypes: ["Sensitive", "Normal", "Dry"], budgets: ["budget"] }, notes: "No-nasties UK brand, fragrance-free" },
  { name: "Garnier SkinActive Micellar Cleansing Water", category: "Cleanser", brand: "Garnier", clean: false, price: 9, affiliateUrl: "https://www.amazon.com/", tags: { concerns: ["Sensitivity"], skinTypes: ["Normal", "Combination", "Sensitive"], budgets: ["budget"] }, notes: "Drugstore micellar classic" },
  { name: "Pixi Glow Tonic", category: "Toner", brand: "Pixi", clean: true, price: 15, affiliateUrl: "https://www.target.com/", tags: { concerns: ["Dullness", "Uneven Texture", "Large Pores"], skinTypes: ["Normal", "Oily", "Combination"], budgets: ["budget"] }, notes: "5% glycolic acid cult toner" },
  { name: "Milani Make It Last Setting Spray SPF 50", category: "Sunscreen", brand: "Milani", clean: false, price: 14, affiliateUrl: "https://www.ulta.com/", tags: { concerns: ["Large Pores"], skinTypes: ["Oily", "Combination", "Normal"], budgets: ["budget"] }, notes: "Budget SPF setting spray" },
];

// ===== REFERENCE DATA =====

export const CONCERNS: Concern[] = [
  "Acne",
  "Hyperpigmentation",
  "Dark Spots",
  "Fine Lines",
  "Wrinkles",
  "Dullness",
  "Large Pores",
  "Uneven Texture",
  "Dark Circles",
  "Dehydration",
  "Redness",
  "Sensitivity",
];

export const CONCERN_DESCRIPTIONS: Record<Concern, string> = {
  "Acne": "Breakouts, clogged pores, blemishes",
  "Hyperpigmentation": "Uneven skin tone, post-inflammatory marks",
  "Dark Spots": "Sun spots, age spots, melasma",
  "Fine Lines": "Early signs of aging, expression lines",
  "Wrinkles": "Deeper creases, loss of elasticity",
  "Dullness": "Lack of radiance, tired-looking skin",
  "Large Pores": "Visible pores, especially on nose and cheeks",
  "Uneven Texture": "Rough patches, bumpy skin",
  "Dark Circles": "Under-eye darkness, tired appearance",
  "Dehydration": "Tight, flaky, or parched feeling",
  "Redness": "Flushing, visible redness, irritation",
  "Sensitivity": "Reactive skin, easily irritated",
};

export const SKIN_TYPES: SkinType[] = ["Oily", "Dry", "Combination", "Normal", "Sensitive"];

export const SKIN_TYPE_DESCRIPTIONS: Record<SkinType, string> = {
  "Oily": "Shiny, enlarged pores, excess sebum production",
  "Dry": "Tight, flaky, rough patches, feels dehydrated",
  "Combination": "Oily T-zone (forehead, nose, chin), dry cheeks",
  "Normal": "Balanced, minimal issues, not too oily or dry",
  "Sensitive": "Reactive, easily irritated, prone to redness",
};

export const ACNE_TYPES = [
  { id: "hormonal" as const, name: "Hormonal Acne", desc: "Jawline/chin breakouts, cyclic pattern, often deep and painful" },
  { id: "fungal" as const, name: "Fungal Acne", desc: "Small uniform bumps, itchy, common on forehead/chest" },
  { id: "inflammatory" as const, name: "Inflammatory Acne", desc: "Cystic, painful red nodules, swelling" },
  { id: "comedonal" as const, name: "Comedonal Acne", desc: "Blackheads and whiteheads, not inflamed" },
];

export const BUDGET_RANGES = [
  { id: "budget" as const, name: "Budget-Friendly", desc: "$5-25 per product", icon: "💰", priceRange: [0, 25] },
  { id: "mid" as const, name: "Mid-Range", desc: "$25-60 per product", icon: "💎", priceRange: [25, 60] },
  { id: "luxury" as const, name: "Luxury", desc: "$60-150+ per product", icon: "✨", priceRange: [60, 500] },
  { id: "mixed" as const, name: "Mixed Budget", desc: "Splurge on actives, save on basics", icon: "🎯", priceRange: [0, 500] },
];

export const PRODUCT_TYPES: ProductCategory[] = [
  "Cleanser", "Double Cleanser", "Toner", "Essence", "Serum", "Treatment",
  "Moisturizer", "Sunscreen", "Eye Cream", "Exfoliant", "Mask",
  "Retinol", "Vitamin C", "Niacinamide", "Hyaluronic Acid", "Face Oil"
];
